version: "3"
services:
  air:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - go_todo_api
  mysql:
    image: mysql:8.0.29-oracle
    container_name: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - go_todo_api
    ports:
      - "3306:3306"
networks:
  go_todo_api: